name: Scala CI

on:
  push:
    branches: [ master, develop, feature/* ]
  pull_request:
    branches: [ master, develop, feature/* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
    - name: Run tests
      run: sbt coverageOn clean test coverageReport scalastyle scapegoat
